### PR TITLE
In 499 test directory checker v1.1.0 - minor fixes

### PR DESCRIPTION
**Pull request by Yu-jinKim**
- Fix the unittest command to run
- Fix the search for replaced tests to NOT match stuff like R15 and R150

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_checker/10)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_checker/10)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Yu-jinKim)

___
*[`test_directory_checker/checker.py` line 136 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_checker/10#-NtqL-322nJIFfLW-eBT:-NtqL-322nJIFfLW-eBU:bv4lxnq) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/d4dd8dcf423e3b03240d6ac38275dc581a83d84e/test_directory_checker/checker.py#L136)):*
> ```Python
>             # equivalence
>             td_for_r_code = td_data[
>                 td_data["Test ID"].str.contains(f"^{r_code.split('.')[0]}\.")
> ```

have you got tests for this? what is the difference from before in what you're matching?



_Code quote:_
```Python
(f"^{r_code.split('.')[0]}\.")
```

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_checker/10)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`test_directory_checker/checker.py` line 136 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_checker/10#-NtqL-322nJIFfLW-eBT:-NtunfNE59kbZIu1Dc4A:b5mnhnb) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/d4dd8dcf423e3b03240d6ac38275dc581a83d84e/test_directory_checker/checker.py#L136)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

have you got tests for this? what is the difference from before in what you're matching?
</blockquote></details>

```
Name                                 Stmts   Miss  Cover   Missing
------------------------------------------------------------------
test_directory_checker/checker.py       87      5    94%   95-96, 240, 246-247
test_directory_checker/identify.py      55     26    53%   77-130
test_directory_checker/output.py        28     14    50%   21-30, 41-42, 55-65
test_directory_checker/utils.py         83     21    75%   17, 32-37, 51-72, 85-88, 101, 116-119, 146, 224, 279-280
tests/__init__.py                        0      0   100%
tests/conftest.py                       22      0   100%
tests/test_checker.py                   82      0   100%
------------------------------------------------------------------
TOTAL                                  357     66    82%
```
it is covered.

I was matching R15 with R150 for example so the code change adds a dot in the pattern matching i.e. R15.

**Review by jethror1 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_checker/10)* status: 1 of 2 files reviewed, all discussions resolved

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_checker/10)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Pull request merged**
