### PR TITLE
Test directory checker - everything

### PR DESCRIPTION
**Pull request by Yu-jinKim**
5 main tests:
- Check targets
- Check test methods
- Compare genepanels and test directory
- Find new clinical indications
- Check presence of genes in database

Unittesting outcome:

```
py.test -vvvvv -s tests/test_checker.py --td tests/test_files/test_td.tsv --genepanels test
s/test_files/test_genepanels.tsv --hgnc_dump hgnc_dump.txt --config tests/test_files/test_config.json
================================================================================================ test session starts ================================================================================================
platform linux -- Python 3.8.10, pytest-7.4.2, pluggy-1.3.0 -- /home/kimy/NHS/envs/test_directory_checker/bin/python3
cachedir: .pytest_cache
rootdir: /home/kimy/NHS/repos/test_directory_checker
collected 7 items                                                                                                                                                                                                   

tests/test_checker.py::test_check_target_panel PASSED
tests/test_checker.py::test_check_target_gene PASSED
tests/test_checker.py::test_check_test_method_exists PASSED
tests/test_checker.py::test_check_test_method_not_exists PASSED
tests/test_checker.py::test_compare_gp_td PASSED
tests/test_checker.py::test_find_new_clinical_indications PASSED
tests/test_checker.py::test_check_if_genes_in_db PASSED

=========================================================================================== 7 passed in 156.19s (0:02:36) ===========================================================================================
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1)

### CODE REVIEW

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> Reviewed 13 of 14 files at r1, 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1)* status: 16 of 18 files reviewed, 7 unresolved discussions (waiting on @Yu-jinKim)

___
*[`test_directory_checker/checker.py` line 169 at r2](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NgK1iTuC9IfMcyuBfkK:-NgK1iTuC9IfMcyuBfkL:b2teq9d) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/de13cf366fe213c397792a89aec8df94e412d938/test_directory_checker/checker.py#L169)):*
> ```Python
>             if td_for_r_code.shape[0] == 0:
>                 # clinical indication has been removed
>                 continue
> ```

will the final output html give indication of which clinical indication has been removed from td?
___
*[`test_directory_checker/checker.py` line 205 at r2](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NgK1v6t6xLseX8cf8ZY:-NgK1v6t6xLseX8cf8ZZ:bqn2h01) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/de13cf366fe213c397792a89aec8df94e412d938/test_directory_checker/checker.py#L205)):*
> ```Python
> 
>             elif td_for_r_code.shape[0] >= 2:
>                 # loop through those tests and check if one of them replaces
> ```

how is the check done? I can see below that you're appending both results to replaced_tests
does that mean in the output html, e.g. R123.1 might have R123.3 and R123.4 comparison?
___
*[`test_directory_checker/checker.py` line 282 at r2](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NgK3eG5DfFkIQ6FMXth:-NgK3eG5DfFkIQ6FMXti:bj4cryz) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/de13cf366fe213c397792a89aec8df94e412d938/test_directory_checker/checker.py#L282)):*
> ```Python
>     )
> 
>     for test_code in td_data["Test ID"].unique():
> ```

won't it be better to check if for test_id in td_data that is not present in genepanel_df then that's the df with all the new clinical indication?
```
td_data[~test_data['Test ID'].str.contains('|'.join(genepanel_df['ci'].values))]

```
___
*[`test_directory_checker/identify.py` line 124 at r2](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NgJiAa56U2pniyzRt5K:-NgJiAa56U2pniyzRt5L:b-43x5ae) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/de13cf366fe213c397792a89aec8df94e412d938/test_directory_checker/identify.py#L124)):*
> ```Python
>                 df_res.at["Alias"] = True
> 
>             elif len(df_previous_symbols) >= 1:
> ```

if both previous and alias are >= 1, we go with previous symbols first?
___
*[`test_directory_checker/utils.py` line 82 at r2](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NgJzKek2VcZYTHl7kj3:-NgJzKek2VcZYTHl7kj4:b-4ok69n) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/de13cf366fe213c397792a89aec8df94e412d938/test_directory_checker/utils.py#L82)):*
> ```Python
> 
> 
> def hgnc_query(hgnc_id, hgnc_dump):
> ```

i'm bias to say docstring but this function is abit short for that, but still, docstring please
___
*[`test_directory_checker/utils.py` line 121 at r2](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NgJzREq4iYZZF-Zw67n:-NgJzREq4iYZZF-Zw67o:b9h4v8) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/de13cf366fe213c397792a89aec8df94e412d938/test_directory_checker/utils.py#L121)):*
> ```Python
> 
> 
> def get_genes_from_td_target(
> ```

docstring
___
*[`tests/test_checker.py` line 10 at r2](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NgK53RtEhsDlFhRryZq:-NgK53RtEhsDlFhRryZr:buntb3n) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/de13cf366fe213c397792a89aec8df94e412d938/tests/test_checker.py#L10)):*
> ```Python
> 
> 
> def test_check_target(hgnc_dump):
> ```

could you show the result of the unit test in the PR comment please

**Review by JasonLing95 — COMMENTED** [review]
> Reviewed 22 of 22 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1)* status: all files reviewed, 3 unresolved discussions (waiting on @Yu-jinKim)

**Review by corbin-chris — CHANGES_REQUESTED** [review]
> Reviewed 1 of 22 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1)* status: all files reviewed, 15 unresolved discussions (waiting on @JasonLing95 and @Yu-jinKim)

___
*[`main.py` line 31 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NhR7LGVEIA6bbD4Q4iv:-NhR7LGVEIA6bbD4Q4iw:b-55zyve) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/5ee94e982b78a318de85b98ee458b7a906637b80/main.py#L31)):*
> ```Python
>     )
> 
>     gene_locus_type = utils.get_locus_status_genes(
> ```

Some one-line comments to describe why you're doing each step in main would be useful as it's really difficult to tell what's going on just from looking (except for when you're loading all the files).  
___
*[`main.py` line 154 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NhQtHse0zJVUEGizvpR:-NhQtHse0zJVUEGizvpS:bbqp6ul) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/5ee94e982b78a318de85b98ee458b7a906637b80/main.py#L154)):*
> ```Python
> 
>     parser.add_argument(
>         "-c", "--config", help="Test directory parser config file"
> ```

For your '-' flagged args that are mandatory for the code to work, like "-c"/"--config", make sure you set 'required=True'. Otherwise, argparse assumes they are optional, and won't error out immediately if you try to call your checker without a config file: https://docs.python.org/3.8/library/argparse.html#required
You have a default for "-o"/"--output" so maybe you don't need to set 'required' there.
___
*[`test_directory_checker/checker.py` line 12 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NhR3Rqj1rL-9gq0rPup:-NhR3Rqj1rL-9gq0rPuq:b-xwvlht) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/5ee94e982b78a318de85b98ee458b7a906637b80/test_directory_checker/checker.py#L12)):*
> ```Python
> 
> def check_target(row: pd.Series, hgnc_dump: pd.DataFrame) -> pd.Series:
>     """ Check target and return the identified panels and genes
> ```

Please add more detail here, because check_target mainly exists to call identify_target, I had to Ctrl+F back and forth a lot to remember what was going on. Something like writing 'test directory row' instead of just 'target' in the docstring, would probably be sufficient. 
___
*[`test_directory_checker/checker.py` line 52 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NhR-Ukr0t-gEujC0bsy:-NhR-Ukr0t-gEujC0bsz:b-u6dvl8) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/5ee94e982b78a318de85b98ee458b7a906637b80/test_directory_checker/checker.py#L52)):*
> ```Python
>         sorted(list(diff_potential_new_tm))
>     )
>     return row
> ```

Is it worth looking for removed test methods as well (subtracting test_method from test_methods_config) or is this unlikely to be an issue?
___
*[`test_directory_checker/checker.py` line 72 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NhR9N233Df9QxYQwRGo:-NhR9N233Df9QxYQwRGp:b-twlkvz) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/5ee94e982b78a318de85b98ee458b7a906637b80/test_directory_checker/checker.py#L72)):*
> ```Python
>         genepanels_data (pd.DataFrame): Dataframe with the genepanels data
>         hgnc_dump (pd.DataFrame): Dataframe with the HGNC data
>         signedoff_panels (dict): Dict containing the signedoff panels from
> ```

Args out of date here, no type specified for gene_locus_type also.
___
*[`test_directory_checker/checker.py` line 116 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NhRAPHe5-OLGAPGzHif:-NhRAPHe5-OLGAPGzHig:b3csxnd) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/5ee94e982b78a318de85b98ee458b7a906637b80/test_directory_checker/checker.py#L116)):*
> ```Python
> 
>         if td_for_test_id.shape[0] == 1:
>             # found test id in test directory
> ```

This function is very long. I won't mandate you do this, but it might be worth splitting it up in future, to simplify unit testing if nothing else:
* compare_gp_td() is a controller function which looks for test ID, then clinical indication ID if the test ID isn't found
* A separate function is called if you find the test ID, involving the code block indented below 'if td_for_test_id.shape[0]'
* If you don't find the test ID, have a separate function (or 2) to handle looking in the clinical indication ID

Then you can test those child-functions in a way which is fairly straightforward, and use unittest mocks to test compare_gp_td()
___
*[`test_directory_checker/identify.py` line 8 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NhR4Nqk7u9bwTQQIfXv:-NhR4Nqk7u9bwTQQIfXw:bl8y0wz) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/5ee94e982b78a318de85b98ee458b7a906637b80/test_directory_checker/identify.py#L8)):*
> ```Python
> 
> def identify_target(target: str, hgnc_dump: pd.DataFrame) -> list:
>     """ Identify the target as gene or panel using regex
> ```

Please specify that the 'target' is a string extracted from a test directory row - may help people follow what's going on.
___
*[`test_directory_checker/utils.py` line 101 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NhRCL7t7ggVtYisTbqL:-NhRCL7t7ggVtYisTbqM:bv71ima) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/5ee94e982b78a318de85b98ee458b7a906637b80/test_directory_checker/utils.py#L101)):*
> ```Python
>         if target.isdigit():
>             # 481 has been merged with 480
>             if target == "481":
> ```

You have this number "481" in a few places in this script. You explain it here, but not in other places, so it may suffer from maintainability issues (sometimes called a 'magic number'): https://stackoverflow.com/questions/47882/what-are-magic-numbers-and-why-do-some-consider-them-bad)
It might instead be better to have defunct PanelApp IDs be a Python list that is defined once in main() and passed to functions by name when needed, which will make it easier to notice and maintain over time, or even making it be a field fetched from the config file you pass to argparse.
___
*[`test_directory_checker/utils.py` line 204 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NhR6EoQ0nEovOgrrx_y:-NhR6EoQ0nEovOgrrx_z:b-hry5ck) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/5ee94e982b78a318de85b98ee458b7a906637b80/test_directory_checker/utils.py#L204)):*
> ```Python
>     """
> 
>     # Check that the content didn't change
> ```

I understand the rest of the comments for this function just fine, but I don't know what you mean by 'check that the content didn't change'. Could you explain further or is it defunct/in the wrong spot?
___
*[`tests/test_checker.py` line 73 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NhRKvHo4O3H_h6U6-5B:-NhRKvHo4O3H_h6U6-5C:bnv9b2w) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/5ee94e982b78a318de85b98ee458b7a906637b80/tests/test_checker.py#L73)):*
> ```Python
> 
> 
> def test_check_target_gene(setup_hgnc_dump):
> ```

Did you check that the function gets rid of the weird dashes anywhere?
___
*[`tests/test_checker.py` line 119 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NhRL7Pt6kgfy73dmSOY:-NhRL7Pt6kgfy73dmSOZ:byznlro) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/5ee94e982b78a318de85b98ee458b7a906637b80/tests/test_checker.py#L119)):*
> ```Python
> 
> def test_check_test_method_not_exists(setup_config):
>     """ Test that finds a new test method
> ```

Tell us in the docstring what you expect to have happen in this test case, e.g. the function labels the returned row in a certain way.
___
*[`tests/test_checker.py` line 349 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NhRLkEE9AxGNAUvGp9_:-NhRLkEE9AxGNAUvGp9a:b8umq6l) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/5ee94e982b78a318de85b98ee458b7a906637b80/tests/test_checker.py#L349)):*
> ```Python
> 
> 
> def test_check_if_genes_in_db(
> ```

Again, docstring to detail what you expect to happen

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1)* status: 23 of 28 files reviewed, 15 unresolved discussions (waiting on @corbin-chris and @JasonLing95)

___
*[`main.py` line 154 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NhQtHse0zJVUEGizvpR:-NhRpp2l9BKu8ZG8_zqB:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/5ee94e982b78a318de85b98ee458b7a906637b80/main.py#L154)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

For your '-' flagged args that are mandatory for the code to work, like "-c"/"--config", make sure you set 'required=True'. Otherwise, argparse assumes they are optional, and won't error out immediately if you try to call your checker without a config file: https://docs.python.org/3.8/library/argparse.html#required
You have a default for "-o"/"--output" so maybe you don't need to set 'required' there.
</blockquote></details>

Done.
___
*[`test_directory_checker/checker.py` line 169 at r2](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NgK1iTuC9IfMcyuBfkK:-NgNcxtsE0u7iIi97dmj:b-11c3fx) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/de13cf366fe213c397792a89aec8df94e412d938/test_directory_checker/checker.py#L169)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

will the final output html give indication of which clinical indication has been removed from td?
</blockquote></details>

Added new output html, done.
___
*[`test_directory_checker/checker.py` line 205 at r2](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NgK1v6t6xLseX8cf8ZY:-NgNbCJD0QSiG7GUHsN3:b1r3nl3) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/de13cf366fe213c397792a89aec8df94e412d938/test_directory_checker/checker.py#L205)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

how is the check done? I can see below that you're appending both results to replaced_tests
does that mean in the output html, e.g. R123.1 might have R123.3 and R123.4 comparison?
</blockquote></details>

yes, i thought it best to check every single new test coming in
___
*[`test_directory_checker/checker.py` line 282 at r2](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NgK3eG5DfFkIQ6FMXth:-NgNqqSMBNtsxW6Po-bR:bpy3htn) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/de13cf366fe213c397792a89aec8df94e412d938/test_directory_checker/checker.py#L282)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

won't it be better to check if for test_id in td_data that is not present in genepanel_df then that's the df with all the new clinical indication?
```
td_data[~test_data['Test ID'].str.contains('|'.join(genepanel_df['ci'].values))]

```
</blockquote></details>

rewrote using your input thanks, done.
___
*[`test_directory_checker/checker.py` line 52 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NhR-Ukr0t-gEujC0bsy:-NhRrnlU87e_gdpOK87E:bkojvs9) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/5ee94e982b78a318de85b98ee458b7a906637b80/test_directory_checker/checker.py#L52)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Is it worth looking for removed test methods as well (subtracting test_method from test_methods_config) or is this unlikely to be an issue?
</blockquote></details>

I did that before but it made no sense since removing the test method from the other methods just returned the big list of test methods.
Maybe the solution be to look at the outcome of the difference and put a True/False for potential new/removed test methods
___
*[`test_directory_checker/checker.py` line 72 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NhR9N233Df9QxYQwRGo:-NhRrkT15IfD24-G18Rd:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/5ee94e982b78a318de85b98ee458b7a906637b80/test_directory_checker/checker.py#L72)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Args out of date here, no type specified for gene_locus_type also.
</blockquote></details>

Done.
___
*[`test_directory_checker/identify.py` line 124 at r2](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NgJiAa56U2pniyzRt5K:-NgNdgp2A9rMjM46P62l:b-x9u12) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/de13cf366fe213c397792a89aec8df94e412d938/test_directory_checker/identify.py#L124)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

if both previous and alias are >= 1, we go with previous symbols first?
</blockquote></details>

yes, but it shouldn't come to that because i have an if for `previous_symbols >= 1 and alias_symbols >= 1` 
___
*[`test_directory_checker/identify.py` line 8 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NhR4Nqk7u9bwTQQIfXv:-NhRsr9J-ZjXHNduDFyP:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/5ee94e982b78a318de85b98ee458b7a906637b80/test_directory_checker/identify.py#L8)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Please specify that the 'target' is a string extracted from a test directory row - may help people follow what's going on.
</blockquote></details>

Done.
___
*[`test_directory_checker/utils.py` line 82 at r2](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NgJzKek2VcZYTHl7kj3:-NgNeLBa8gptyZ2HqPoY:bi9q9a2) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/de13cf366fe213c397792a89aec8df94e412d938/test_directory_checker/utils.py#L82)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

i'm bias to say docstring but this function is abit short for that, but still, docstring please
</blockquote></details>

removed function since it was a oneliner
___
*[`test_directory_checker/utils.py` line 121 at r2](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NgJzREq4iYZZF-Zw67n:-NgNfMel9MDVrMOOZCSM:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/de13cf366fe213c397792a89aec8df94e412d938/test_directory_checker/utils.py#L121)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

docstring
</blockquote></details>

Done.
___
*[`test_directory_checker/utils.py` line 101 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NhRCL7t7ggVtYisTbqL:-NhS-CED3XwD1TSk3H7V:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/5ee94e982b78a318de85b98ee458b7a906637b80/test_directory_checker/utils.py#L101)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

You have this number "481" in a few places in this script. You explain it here, but not in other places, so it may suffer from maintainability issues (sometimes called a 'magic number'): https://stackoverflow.com/questions/47882/what-are-magic-numbers-and-why-do-some-consider-them-bad)
It might instead be better to have defunct PanelApp IDs be a Python list that is defined once in main() and passed to functions by name when needed, which will make it easier to notice and maintain over time, or even making it be a field fetched from the config file you pass to argparse.
</blockquote></details>

Done.
___
*[`test_directory_checker/utils.py` line 204 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NhR6EoQ0nEovOgrrx_y:-NhS0PNB6foYlo-Y0jRi:b-4tqh8g) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/5ee94e982b78a318de85b98ee458b7a906637b80/test_directory_checker/utils.py#L204)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

I understand the rest of the comments for this function just fine, but I don't know what you mean by 'check that the content didn't change'. Could you explain further or is it defunct/in the wrong spot?
</blockquote></details>

defunct, Done
___
*[`tests/test_checker.py` line 10 at r2](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NgK53RtEhsDlFhRryZq:-NhS0S1jCquo1ya4dmX3:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/de13cf366fe213c397792a89aec8df94e412d938/tests/test_checker.py#L10)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

could you show the result of the unit test in the PR comment please
</blockquote></details>

Done.

**Review by corbin-chris — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1)* status: 26 of 28 files reviewed, 14 unresolved discussions (waiting on @JasonLing95 and @Yu-jinKim)

___
*[`main.py` line 31 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NhR7LGVEIA6bbD4Q4iv:-NhVozMgCwuycH678Q8W:b-25yppb) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/5ee94e982b78a318de85b98ee458b7a906637b80/main.py#L31)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Some one-line comments to describe why you're doing each step in main would be useful as it's really difficult to tell what's going on just from looking (except for when you're loading all the files).
</blockquote></details>

Thanks, looking better. 
___
*[`main.py` line 154 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NhQtHse0zJVUEGizvpR:-NhVpssZAQJZWjI4M-ua:b-w53znk) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/5ee94e982b78a318de85b98ee458b7a906637b80/main.py#L154)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see a change in the code?
___
*[`test_directory_checker/utils.py` line 101 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NhRCL7t7ggVtYisTbqL:-NhVqiOF9WERLL2Aaxju:b-yywadj) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/5ee94e982b78a318de85b98ee458b7a906637b80/test_directory_checker/utils.py#L101)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No, please put your panel IDs (481 and now 1218 too?) in a single list defined either in main or in a config file. This absolutely will fall out of date in half the places in the script otherwise.

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1)* status: 26 of 28 files reviewed, 14 unresolved discussions (waiting on @corbin-chris and @JasonLing95)

___
*[`main.py` line 154 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NhQtHse0zJVUEGizvpR:-NhVyPJ2CE2-7VExxRoV:bz2mvb0) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/5ee94e982b78a318de85b98ee458b7a906637b80/main.py#L154)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

I don't see a change in the code?
</blockquote></details>

i don't know what is going on with the repo

___
*[`test_directory_checker/utils.py` line 101 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NhRCL7t7ggVtYisTbqL:-NhVyfWj7kijx1jrpSRs:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/5ee94e982b78a318de85b98ee458b7a906637b80/test_directory_checker/utils.py#L101)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

No, please put your panel IDs (481 and now 1218 too?) in a single list defined either in main or in a config file. This absolutely will fall out of date in half the places in the script otherwise.
</blockquote></details>

Done.

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1)* status: 22 of 29 files reviewed, 14 unresolved discussions (waiting on @corbin-chris and @JasonLing95)

___
*[`main.py` line 31 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NhR7LGVEIA6bbD4Q4iv:-NhW2JRk1y83-PBBqpl1:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/5ee94e982b78a318de85b98ee458b7a906637b80/main.py#L31)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Thanks, looking better.
</blockquote></details>

Done.
___
*[`test_directory_checker/checker.py` line 12 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NhR3Rqj1rL-9gq0rPup:-NhW3BrZ3DUz963z2RYN:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/5ee94e982b78a318de85b98ee458b7a906637b80/test_directory_checker/checker.py#L12)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Please add more detail here, because check_target mainly exists to call identify_target, I had to Ctrl+F back and forth a lot to remember what was going on. Something like writing 'test directory row' instead of just 'target' in the docstring, would probably be sufficient.
</blockquote></details>

Done.
___
*[`test_directory_checker/checker.py` line 116 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NhRAPHe5-OLGAPGzHif:-NhW3DRr9hxzGt4l70tv:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/5ee94e982b78a318de85b98ee458b7a906637b80/test_directory_checker/checker.py#L116)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

This function is very long. I won't mandate you do this, but it might be worth splitting it up in future, to simplify unit testing if nothing else:
* compare_gp_td() is a controller function which looks for test ID, then clinical indication ID if the test ID isn't found
* A separate function is called if you find the test ID, involving the code block indented below 'if td_for_test_id.shape[0]'
* If you don't find the test ID, have a separate function (or 2) to handle looking in the clinical indication ID

Then you can test those child-functions in a way which is fairly straightforward, and use unittest mocks to test compare_gp_td()
</blockquote></details>

Done.
___
*[`tests/test_checker.py` line 119 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NhRL7Pt6kgfy73dmSOY:-NhW4BtUEs0BqNnPt1rc:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/5ee94e982b78a318de85b98ee458b7a906637b80/tests/test_checker.py#L119)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Tell us in the docstring what you expect to have happen in this test case, e.g. the function labels the returned row in a certain way.
</blockquote></details>

Done.
___
*[`tests/test_checker.py` line 349 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1#-NhRLkEE9AxGNAUvGp9_:-NhW4W7q7iFcxHvxk5lG:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_checker/blob/5ee94e982b78a318de85b98ee458b7a906637b80/tests/test_checker.py#L349)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Again, docstring to detail what you expect to happen
</blockquote></details>

Done.

**Review by corbin-chris — COMMENTED** [review]
> Reviewed 6 of 7 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1)* status: all files reviewed, 4 unresolved discussions (waiting on @JasonLing95 and @Yu-jinKim)

**Review by Yu-jinKim — COMMENTED** [review]
> Dismissed @JasonLing95 from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1)* status: all files reviewed, 1 unresolved discussion (waiting on @corbin-chris)

**Review by corbin-chris — APPROVED** [review]
> Dismissed @JasonLing95 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_checker/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Pull request merged**
